// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Ship.proto

/*
Package protobuff is a generated protocol buffer package.

It is generated from these files:
	Ship.proto

It has these top-level messages:
	Ship
*/
package protobuff

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Ship struct {
	Shipname    string             `protobuf:"bytes,1,opt,name=shipname" json:"shipname,omitempty"`
	CaptainName string             `protobuf:"bytes,2,opt,name=CaptainName" json:"CaptainName,omitempty"`
	Crew        []*Ship_CrewMember `protobuf:"bytes,3,rep,name=Crew" json:"Crew,omitempty"`
}

func (m *Ship) Reset()                    { *m = Ship{} }
func (m *Ship) String() string            { return proto.CompactTextString(m) }
func (*Ship) ProtoMessage()               {}
func (*Ship) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Ship) GetShipname() string {
	if m != nil {
		return m.Shipname
	}
	return ""
}

func (m *Ship) GetCaptainName() string {
	if m != nil {
		return m.CaptainName
	}
	return ""
}

func (m *Ship) GetCrew() []*Ship_CrewMember {
	if m != nil {
		return m.Crew
	}
	return nil
}

type Ship_CrewMember struct {
	Id           int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	SecClearance int32  `protobuf:"varint,3,opt,name=secClearance" json:"secClearance,omitempty"`
	Position     string `protobuf:"bytes,4,opt,name=position" json:"position,omitempty"`
}

func (m *Ship_CrewMember) Reset()                    { *m = Ship_CrewMember{} }
func (m *Ship_CrewMember) String() string            { return proto.CompactTextString(m) }
func (*Ship_CrewMember) ProtoMessage()               {}
func (*Ship_CrewMember) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Ship_CrewMember) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Ship_CrewMember) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Ship_CrewMember) GetSecClearance() int32 {
	if m != nil {
		return m.SecClearance
	}
	return 0
}

func (m *Ship_CrewMember) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func init() {
	proto.RegisterType((*Ship)(nil), "protobuff.Ship")
	proto.RegisterType((*Ship_CrewMember)(nil), "protobuff.Ship.CrewMember")
}

func init() { proto.RegisterFile("Ship.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x41, 0xae, 0x82, 0x30,
	0x10, 0x86, 0x03, 0xf4, 0xbd, 0xc8, 0x60, 0x5c, 0xcc, 0xaa, 0x61, 0x45, 0x58, 0xb1, 0xea, 0x42,
	0x8f, 0xc0, 0x5a, 0x17, 0x78, 0x82, 0x02, 0x25, 0x34, 0x91, 0xb6, 0x29, 0x18, 0x6f, 0xec, 0x39,
	0x4c, 0xc7, 0x08, 0xba, 0x6a, 0xe7, 0xff, 0x26, 0xf9, 0xe6, 0x07, 0xb8, 0x8e, 0xda, 0x09, 0xe7,
	0xed, 0x62, 0x31, 0xa5, 0xa7, 0xbd, 0x0f, 0x43, 0xf9, 0x8c, 0x80, 0x05, 0x82, 0x39, 0xec, 0xe6,
	0x51, 0x3b, 0x23, 0x27, 0xc5, 0xa3, 0x22, 0xaa, 0xd2, 0x66, 0x9d, 0xb1, 0x80, 0xac, 0x96, 0x6e,
	0x91, 0xda, 0x5c, 0x02, 0x8e, 0x09, 0x7f, 0x47, 0x28, 0x80, 0xd5, 0x5e, 0x3d, 0x78, 0x52, 0x24,
	0x55, 0x76, 0xcc, 0xc5, 0x2a, 0x10, 0xa4, 0x0d, 0xec, 0xac, 0xa6, 0x56, 0xf9, 0x86, 0xf6, 0x72,
	0x07, 0xb0, 0x65, 0x78, 0x80, 0x58, 0xf7, 0x64, 0xfd, 0x6b, 0x62, 0xdd, 0x23, 0x02, 0x33, 0x9b,
	0x88, 0xfe, 0x58, 0xc2, 0x7e, 0x56, 0x5d, 0x7d, 0x53, 0xd2, 0x4b, 0xd3, 0x29, 0x9e, 0xd0, 0xf6,
	0x4f, 0x16, 0x3a, 0x38, 0x3b, 0xeb, 0x45, 0x5b, 0xc3, 0xd9, 0xbb, 0xc3, 0x67, 0x6e, 0xff, 0xe9,
	0xa4, 0xd3, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x6d, 0x32, 0x22, 0xc5, 0x08, 0x01, 0x00, 0x00,
}
